- shell: |
    echo "#$(uuidgen)"
    echo "#$(uuidgen)"
  register: cmd_uuid_gen

- set_fact: 
    interaction_id: '{{ cmd_uuid_gen.stdout_lines[0] }}'  
  when: interaction_id is not defined

- name: "Execute command"
  community.aws.execute_lambda:
    name: '{{ params["EnvironmentNameUpper"] }}-user-svc' 
    payload:
      interaction-id: '{{ interaction_id }}'
      request-id: '{{ cmd_uuid_gen.stdout_lines[1] }}'
      commands: 
      - '{{ body }}'
      meta: 
        realm: prod
    wait: true
  register: cmd_response

- fail: 
    msg: "Command error"
  when: cmd_response.result.output.result.success != true

- set_fact: 
    cmd_response: '{{ cmd_response.result.output }}'

