- shell: |
    echo "#$(uuidgen)"
  register: agg_uuid_gen

- include_tasks: query.yml
  vars: 
    body: '{{ query_body }}'

- set_fact:
    aggregate_id: '{{ query_response.result.id | default(agg_uuid_gen.stdout_lines[0]) }}' 

- debug: 
    var: aggregate_id

- include_tasks: cmd.yml
  vars: 
    body: '{{ cmd_body | combine({"id" : aggregate_id}) }}'
  when: query_response.result == None

