- include_tasks: create_missing.yml
  vars: 
    query_body: 
      query-id: ":get-by-name" 
      name: '{{ params["ServiceName"] }}' 
    cmd_body: 
      cmd-id: ":create-application" 
      attrs: 
        name: '{{ params["ServiceName"] }}' 

- set_fact: 
    application_id: '{{ aggregate_id }}'

- include_tasks: create_missing.yml
  vars:
    query_body: 
      query-id: ":get-by-email" 
      email: '{{ item }}' 
    cmd_body: 
      cmd-id: ":create-user" 
      attrs: 
        email: '{{ item }}' 
  loop: '{{ admins }}'
  when: admins

- include_tasks: cmd.yml
  vars:
    body: 
      id: '{{ application_id }}'
      cmd-id: ":add-admins" 
      attrs: 
        email: '{{ admins }}' 
  when: admins

- set_fact:
    params: '{{ params | combine( {"ApplicationId" : application_id} ) }}'
