AWSTemplateFormatVersion: "2010-09-09"
Description: "CF Template for Lambda function deployment"
Parameters:
  BuildId:
    Type: String

  EnvironmentNameLower:
    Type: String

  EnvironmentNameUpper:
    Type: String

  DeploymentS3BucketName:
    Type: String

  LambdaMemorySize:
    Type: Number
    Default: 128

  LambdaTimeout:
    Type: Number
    Default: 110

  ReservedConcurrentExecutions:
    Type: Number
    Default: 25

  LambdaFunctionHandler:
    Type: String
    Default: 'index.handler'

  LambdaRuntime: 
    Type: String
    Default: provided

  LambdaFunctionName:
    Type: String

  MainClass:
    Type: String

  Region:
    Type: String

  VPCId:
    Type: String

  ServiceName:
    Type: String

  PublicHostedZoneName:
    Type: String

  PublicHostedZoneId:
    Type: String

  S3LambdaObjectName:
    Type: String

  CertificateArn:
    Type: String


  SubscribeDb:
    Type: String
    Default: "True"

  EnableImport:
    Type: String
    Default: "False"

  QueueTimeout:
    Type: String
    Default: "310"

  AuthUserPoolId:
    Type: String

  AuthUserPoolClientId:
    Type: String

  PrivateSubnet1A:
    Type: String
  PrivateSubnet2A:
    Type: String

  LambdaSecurityGroup:
    Type: String

  CustomConfig:
    Type: String

  Deployment:
    Type: String
    Default: "PUBLIC"

  CustomPolicy:
    Type: String
    Default: ""

Conditions:
  ShouldSubscribe: !Or [ !Equals [ !Ref SubscribeDb, "True" ], !Equals [ !Ref SubscribeDb, "true" ] ]
  IsEnableImport: !Or [ !Equals [ !Ref EnableImport, "True" ], !Equals [ !Ref EnableImport, "true" ] ]
  IsInVpc: !Equals [ !Ref Deployment, "VPC" ]
  HasCustmPolicy: !Not [ !Equals [ !Ref CustomPolicy, "" ] ]

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      RoleName: !Sub "${EnvironmentNameUpper}-${LambdaFunctionName}-Role"

  LambdaPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "${EnvironmentNameUpper}-${LambdaFunctionName}-Policy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: BasicPolicy
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ec2:DescribeClientVpnTargetNetworks
              - ec2:DescribeClientVpnEndpoints
              - ec2:ApplySecurityGroupsToClientVpnTargetNetwork
              - ec2:DescribeClientVpnConnections
              - ec2:TerminateClientVpnConnections
              - s3:PutObject
              - s3:GetObject
              - s3:*
              - cognito-idp:AdminInitiateAuth
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:*
            Resource: !Sub "arn:aws:sqs:${Region}:${AWS::AccountId}:${EnvironmentNameLower}*"
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ChangeMessageVisibility
            Resource: !GetAtt CommandsQueue.Arn
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ChangeMessageVisibility
            Resource: !GetAtt EventsQueue.Arn
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource: "*"
      Roles:
        - !Ref LambdaRole

  CustomLambdaPolicy:
    Type: "AWS::IAM::Policy"
    Condition: HasCustmPolicy
    Properties:
      PolicyName: !Sub "${EnvironmentNameUpper}-${LambdaFunctionName}-CustomPolicy"
      PolicyDocument: !Ref CustomPolicy
      Roles:
        - !Ref LambdaRole


  LambdaFunction:
    Type: "AWS::Lambda::Function"
    DependsOn:
      - LambdaPolicy
    Properties:
      FunctionName: !Sub "${EnvironmentNameUpper}-${LambdaFunctionName}"
      Handler: !Sub "${LambdaFunctionHandler}"
      Role: !GetAtt LambdaRole.Arn
      Runtime: !Ref LambdaRuntime
      MemorySize: !Sub "${LambdaMemorySize}"
      Timeout: !Sub "${LambdaTimeout}"
      ReservedConcurrentExecutions: !Ref ReservedConcurrentExecutions
      TracingConfig:
        Mode: "PassThrough"
      Code:
        S3Bucket: !Sub "${DeploymentS3BucketName}"
        S3Key: !Sub "${S3LambdaObjectName}"
      VpcConfig: !If
        - IsInVpc
        - SecurityGroupIds:
            - !Ref LambdaSecurityGroup
          SubnetIds:
            - !Ref PrivateSubnet1A
            - !Ref PrivateSubnet2A
        - !Ref AWS::NoValue
      Environment:
        Variables:
          EnvironmentNameUpper: !Ref EnvironmentNameUpper
          EnvironmentNameLower: !Ref EnvironmentNameLower
          PublicHostedZoneName: !Ref PublicHostedZoneName
          PrivateHostedZoneName: !Ref PublicHostedZoneName
          AuthUserPoolId: !Ref AuthUserPoolId
          AuthUserPoolClientId: !Ref AuthUserPoolClientId
          ServiceName: !Ref ServiceName
          Region: !Ref Region
          BuildId: !Ref BuildId
          AccountId: !Sub "${AWS::AccountId}"
          CustomConfig: !Ref CustomConfig
          MainClass: !Ref MainClass

  LambdaInvokeAPIGWPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
    DependsOn:
      - LambdaFunction
     
  CommandsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${EnvironmentNameLower}-${ServiceName}-commands"
      DelaySeconds: 0
      VisibilityTimeout: !Ref QueueTimeout

  EventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${EnvironmentNameLower}-${ServiceName}-events"
      DelaySeconds: 0
      VisibilityTimeout: !Ref QueueTimeout

  EventsQueueLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt EventsQueue.Arn
      FunctionName: !Ref LambdaFunction

  CommandsQueueLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt CommandsQueue.Arn
      FunctionName: !Ref LambdaFunction

  EventsQueuePermissions:
    Type: AWS::SQS::QueuePolicy
    Condition: ShouldSubscribe
    DependsOn:
      - LambdaPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Principal: "*"
            Resource: !GetAtt EventsQueue.Arn
      Queues:
        - !Ref EventsQueue

  CommandsQueuePermissions:
    Type: AWS::SQS::QueuePolicy
    Condition: ShouldSubscribe
    DependsOn:
      - LambdaPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Principal: "*"
            Resource: !GetAtt CommandsQueue.Arn
      Queues:
        - !Ref CommandsQueue

  EventsSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      BatchSize: 1
      EventSourceArn: !GetAtt EventsQueue.Arn
      FunctionName: !Ref LambdaFunction

  CommandsSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      BatchSize: 1
      EventSourceArn: !GetAtt CommandsQueue.Arn
      FunctionName: !Ref LambdaFunction


  BucketLambdaPermissions:
    Type: AWS::Lambda::Permission
    Condition: IsEnableImport
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${AWS::AccountId}-${EnvironmentNameLower}-${ServiceName}-import'
      SourceAccount: !Ref AWS::AccountId

  LambdaBucketPolicy:
    Type: AWS::IAM::Policy
    Condition: IsEnableImport
    Properties:
      PolicyName: LambdaBuckerImportPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource: !GetAtt Bucket.Arn
      Roles:
        - !Ref LambdaRole

  Bucket:
    Type: AWS::S3::Bucket
    Condition: IsEnableImport
    DependsOn:
      - S3QueuePermissions
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${EnvironmentNameLower}-${ServiceName}'
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt S3Queue.Arn
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  BucketPolicyData:
    Type: AWS::S3::BucketPolicy
    Condition: IsEnableImport
    Properties:
      PolicyDocument:
        Id: BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: "OnlyHTTPS"
            Action: s3:*
            Effect: Deny
            Principal: "*"
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
              - !Sub "arn:aws:s3:::${Bucket}"
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: ReadWrite
            Effect: Allow
            Principal: "*"
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/*"
              - !Sub "arn:aws:s3:::${Bucket}"
            Condition:
              StringLike:
                "aws:PrincipalArn": !Sub "arn:aws:iam::${AWS::AccountId}:role/${EnvironmentNameUpper}-${ServiceName}-*"
      Bucket: !Ref Bucket

  S3Queue:
    Type: AWS::SQS::Queue
    Condition: IsEnableImport
    Properties:
      QueueName: !Sub "${EnvironmentNameLower}-${ServiceName}-s3"
      DelaySeconds: 0
      VisibilityTimeout: 120

  S3QueueLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Condition: IsEnableImport
    Properties:
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt S3Queue.Arn
      FunctionName: !Ref LambdaFunction

  S3QueueSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Condition: IsEnableImport
    Properties:
      Enabled: true
      BatchSize: 1
      EventSourceArn: !GetAtt S3Queue.Arn
      FunctionName: !Ref LambdaFunction

  S3QueuePermissions:
    Type: AWS::SQS::QueuePolicy
    Condition: IsEnableImport
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Principal: "*"
            Resource: !GetAtt S3Queue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::${AWS::AccountId}-${EnvironmentNameLower}-${ServiceName}'

      Queues:
        - !Ref S3Queue


Outputs:
  LambdaFunction:
    Description: Arn of the lambda function
    Value: !GetAtt LambdaFunction.Arn
  LambdaRoleArn:
    Description: Arn of the lambda function
    Value: !GetAtt LambdaRole.Arn
  LambdaRoleName:
    Value: !Ref LambdaRole
